# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!

tasks:
  twitch:
    cmds:
      - poetry run python -m souf_twitch_bot
  
  game:
    cmds:
      - poetry run python -m souf_game
